### Реализовать $QR-$разложение при помощи отражений Хаусхолдера для прямоугольной матрицы полного столбцевого ранга. Решить задачу наименьших квадратов на основе полученного разложения.

In [1]:
import numpy as np

def householder_qr(A):
    """
    Вычисляет QR-разложение матрицы A с использованием отражений Хаусхолдера.

    Args:
        A: np.array - Прямоугольная матрица (m x n) полного столбцевого ранга (m >= n).

    Returns:
        Q: np.array - Ортогональная матрица (m x m).
        R: np.array - Верхняя треугольная матрица (m x n), где элементы под главной диагональю - нули.
    """
    m, n = A.shape
    Q = np.eye(m) 
    R = A.copy()

    for k in range(n):
        x = R[k:, k]
        v = x.copy()

        v[0] = v[0] + np.sign(v[0]) * np.linalg.norm(x)
        v = v / np.linalg.norm(v)

        H = np.eye(m)
        H[k:, k:] = H[k:, k:] - 2 * np.outer(v, v)

        R = H @ R

        Q = Q @ H.T

    return Q, R


def solve_least_squares(Q, R, b):
    """
    Решает задачу наименьших квадратов Ax = b, используя QR-разложение.

    Args:
        Q: np.array - Ортогональная матрица (m x m) из QR-разложения.
        R: np.array - Верхняя треугольная матрица (m x n) из QR-разложения.
        b: np.array - Вектор (m x 1).

    Returns:
        x: np.array - Решение задачи наименьших квадратов (n x 1).
    """
    m, n = R.shape

    y = Q.T @ b

    R_reduced = R[:n, :]
    y_reduced = y[:n]

    x = np.linalg.solve(R_reduced, y_reduced)

    return x

In [2]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=float)
b = np.array([7, 8, 9], dtype=float)

Q, R = householder_qr(A)

x = solve_least_squares(Q, R, b)

print("A =\n", A)
print("b =\n", b)
print("\n")

print("Q =\n", Q)
print("R =\n", R)
print("\n")

print("x =\n", x)
print("\n")

print("===CHECK===")

residual = np.dot(A, x) - b
print("||Ax - b|| =", np.linalg.norm(residual))

A =
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
b =
 [7. 8. 9.]


Q =
 [[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
R =
 [[-5.91607978e+00 -7.43735744e+00]
 [ 2.51141333e-17  8.28078671e-01]
 [ 2.20619779e-16 -8.87765267e-17]]


x =
 [-6.   6.5]


===CHECK===
||Ax - b|| = 8.140289677804162e-15
