### Реализовать $ LDM^\text{T} -$разложение матрицы A, использовать его для проверки положительной определённости матрицы.

In [ ]:
import numpy as np

def LDMT_decomposition(A):
    """
    LDM^T-разложение матрицы А.
    
    Parameters:
        A: Квадратная симметричная положительно определённая матрица.
        
    Returns:
        L, D, M: Матрицы разложения.
    """
    
    n = A.shape[0]

    L = np.eye(n) 
    D = np.zeros((n, n))  
    M = np.eye(n)  
    
    for j in range(n):
        sum_d = 0.0
        for k in range(j):
            sum_d += L[j,k] * D[k,k] * M[j,k]
        D[j,j] = A[j,j] - sum_d
        
        for i in range(j + 1, n):
            sum_l = 0.0
            for k in range(j):
                sum_l += L[i,k] * D[k,k] * M[j,k]
            L[i,j] = (A[i,j] - sum_l) / D[j,j]
            
            sum_m = 0.0
            for k in range(j):
                sum_m += L[j,k] * D[k,k] * M[i,k]
            M[i,j] = (A[j,i] - sum_m) / D[j,j]
    
    return L, D, M

def is_positive_definite(A):
    """
    Проверка положительной определённости матрицы A.

    Args:
        A: Квадратная матрица.

    Returns:
        True, если матрица положительно определена, False - иначе.
    """

    L, D, M = LDMT_decomposition(A)
    return np.all(np.diag(D) > 0)

In [3]:
A = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]], dtype=float)

print("A = \n", A)

B = np.array([[-3, 1, 1],
              [4, -2, 3],
              [8, 7, 9]], dtype=float)

print("B = \n", B)
print("\n")

print("===CHECK===")

print("A > 0: ", is_positive_definite(A))
print("B > 0: ", is_positive_definite(B))

A = 
 [[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]
B = 
 [[-3.  1.  1.]
 [ 4. -2.  3.]
 [ 8.  7.  9.]]


===CHECK===
A > 0:  True
B > 0:  False
