### Реализовать $LDL^T-$разложение симметричной трехдиагональной матрицы $A$. В случае, когда $A$ положительно определена, использовать разложение для решения линейной системы $Ax = b$. Организовать проверку, вычислив $A\^{x} - b$, где $\^{x}$ - найденное решение.

In [1]:
import numpy as np

def LDLT_decomposition_tridiagonal(A):
    """
    Выполняет LDL^T-разложение симметричной трехдиагональной матрицы.

    Аргументы:
        A: np.array - Симметричная трехдиагональная матрица.

    Возвращает:
        D: np.array - Диагональная матрица (представленная в виде одномерного массива).
        L: np.array - Нижняя треугольная матрица с единицами на главной диагонали (представлена в виде одномерного массива).
                      Содержит элементы нижней диагонали.
    """

    n = A.shape[0]
    D = np.zeros(n)
    L = np.zeros(n - 1)

    D[0] = A[0, 0]
    if D[0] == 0:
      return None, None

    for i in range(1, n):
        L[i - 1] = A[i, i - 1] / D[i - 1]
        D[i] = A[i, i] - L[i - 1] * A[i, i - 1]
        if D[i] == 0:
            return None, None

    return D, L


def solve_LDLT_tridiagonal(D, L, b):
    """
    Решает линейную систему Ax = b, где A представлена LDL^T-разложением.

    Аргументы:
        D: np.array - Диагональная матрица (одномерный массив).
        L: np.array - Нижняя треугольная матрица (одномерный массив).
        b: np.array - Вектор правой части.

    Возвращает:
        x: np.array - Решение системы Ax = b.
    """

    n = len(D)
    y = np.zeros(n)
    x = np.zeros(n)

    # Решение Ly = b
    y[0] = b[0]
    for i in range(1, n):
        y[i] = b[i] - L[i - 1] * y[i - 1]

    # Решение Dz = y
    z = y / D

    # Решение L^T x = z
    x[n - 1] = z[n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = z[i] - L[i] * x[i + 1]

    return x


def create_tridiagonal_matrix(a_list, b_list, c_list, n):
    """
    Создает трехдиагональную матрицу из диагоналей.

    Аргументы:
        a_list: list - Значения на главной диагонали.
        b_list: list - Значения на нижней диагонали.
        c_list: list - Значения на верхней диагонали.
        n: int - Размер матрицы.

    Возвращает:
        A: np.array - Трехдиагональная матрица.
    """

    A = np.zeros((n, n))
    for i in range(n):
        A[i, i] = a_list[i]
        if i > 0:
            A[i, i - 1] = b_list[i - 1]
            A[i - 1, i] = c_list[i - 1]
    return A

In [7]:
n = 5
a_list = [3.0, 2.0, 1.0, -1.0, -2.0]  # Элементы главной диагонали
b_list = [-1.0, -2.0, -3.0, 1.0] # Элементы нижней диагонали
c_list = [-1.0, -2.0, -3.0, 1.0] # Элементы верхней диагонали

A = create_tridiagonal_matrix(a_list, b_list, c_list, n)

b = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

D, L = LDLT_decomposition_tridiagonal(A)

print("A =\n", A)
print("\n")
print("D =\n", D)
print("L =\n", L)
print("\n")

x = solve_LDLT_tridiagonal(D, L, b)
print("x =\n", x)
print("\n")

print("===CHECK===")

residual = np.dot(A, x) - b
print("||Ax - b|| =", np.linalg.norm(residual))

A =
 [[ 3. -1.  0.  0.  0.]
 [-1.  2. -2.  0.  0.]
 [ 0. -2.  1. -3.  0.]
 [ 0.  0. -3. -1.  1.]
 [ 0.  0.  0.  1. -2.]]


D =
 [ 3.          1.66666667 -1.4         5.42857143 -2.18421053]
L =
 [-0.33333333 -1.2         2.14285714  0.18421053]


x =
 [ 2.22044605e-16 -1.00000000e+00 -2.00000000e+00 -1.00000000e+00
 -3.00000000e+00]


===CHECK===
||Ax - b|| = 2.3075552236602768e-15
