### Реализовать разложение Холецкого для симметричной, положительно определённой матрицы $ A $, использовать его для решения линейной системы $ Ax = b $ (если $ A $ не является положительно определённой, алгоритм останавливается). Организовать проверку, вычислив $ A\^{x} - b $, где $ \^{x} $ - найденное решение.

In [2]:
import numpy as np

def cholesky_decomposition(A):
    """
    Разложение Холецкого для симметричной, положительно определённой матрицы.

    Args:
        A: Симметричная, положительно определённая матрица.

    Returns:
        L: Нижняя треугольная матрица L, такая что A = LL^T. Возвращает None, если матрица не является положительно определённой.
    """
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i + 1):
            sum_k = sum(L[i, k] * L[j, k] for k in range(j))

            if i == j:
                value = A[i, i] - sum_k
                if value <= 0:
                    print("Матрица не является положительно определённой.")
                    return None
                L[i, i] = np.sqrt(value)
            else:
                if L[j, j] == 0:
                    print("Матрица не является положительно определённой.")
                    return None
                L[i, j] = (1.0 / L[j, j] * (A[i, j] - sum_k))

    return L


def solve_cholesky(A, b):
    """
    Решение линейной системы Ax = b с ипользованием разложения Холецкого.

    Args:
        A: Симметричная, положительно определённая матрица.
        b: Вектор.

    Returns:
        x: Решение.
    """
    L = cholesky_decomposition(A)

    if L is None:
        return None

    y = np.zeros_like(b)
    for i in range(len(b)):
        sum_j = sum(L[i, j] * y[j] for j in range(i))
        y[i] = (b[i] - sum_j) / L[i, i]

    x = np.zeros_like(b)
    for i in range(len(b) - 1, -1, -1):
        sum_j = sum(L[j, i] * x[j] for j in range(i + 1, len(b)))
        x[i] = (y[i] - sum_j) / L[i, i]

    return x


def check_solution(A, x, b):
    """
    Проверка решения линейной системы Ax = b.

    Args:
        A: Матрица.
        x: Решение.
        b: Вектор правой части.

    Returns:
        Вектор (Ax - b).
    """
    return A @ x - b

In [3]:
A = np.array([[2, 1, 1],
                [1, 3, 3],
                [1, 3, 9]], dtype=float)
b = np.array([4, 8, 20], dtype=float)

print("A = \n", A)
print("b = \n", b)
print("\n")

x = solve_cholesky(A, b)
print("x = \n", x)
print("\n")

print("===CHECK===")

residual = check_solution(A, x, b)
print("||Ax - b|| =", np.linalg.norm(residual))

A = 
 [[2. 1. 1.]
 [1. 3. 3.]
 [1. 3. 9.]]
b = 
 [ 4.  8. 20.]


x = 
 [0.8 0.4 2. ]


===CHECK===
||Ax - b|| = 8.881784197001252e-16
