Реализовать разложение Гаусса $ PA = LU $ (с выбором ведущего элемента), использовать его для решения линейной системы $ Ax = b $. Организовать проверку, вычислив $ A \^{x} - b $, где $ \^{x} $ --- найденное решение.

In [6]:
import numpy as np

def LU_decomposition(A):
    """
    LU-разложение матрицы A с выбором ведущего элемента.

    Args:
        A: Квадратная матрица.

    Returns:
        P: Матрица перестановок.
        L: Нижнетреугольная матрица.
        U: Верхнетреугольная матрица.
    """
    n = A.shape[0]

    L = np.eye(n, dtype=float)
    U = A.copy()
    P = np.eye(n, dtype=float)

    for i in range(n - 1):
        leader_idx = np.argmax(np.abs(U[i:, i])) + i

        if leader_idx != i:
            P[[i, leader_idx]] = P[[leader_idx, i]]
            U[[i, leader_idx]] = U[[leader_idx, i]]
            if i > 0:
                L[[i, leader_idx], :i] = L[[leader_idx, i], :i]

        for j in range(i + 1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] = U[j, :] - L[j, i] * U[i, :]

    return P, L, U


def solve_LU(L, U, P, b):
    """
    Решает систему Ax = b, используя LU-разложение.

    Args:
        L: Нижняя треугольная матрица.
        U: Верхняя треугольная матрица.
        P: Матрица перестановок.
        b: Вектор правой части.

    Returns:
        x: Решение системы Ax = b.
    """

    # Решаем Ly = Pb
    Pb = P @ b
    y = np.zeros_like(Pb)
    for i in range(len(Pb)):
        y[i] = Pb[i] - np.dot(L[i, :i], y[:i])

    # Решаем Ux = y
    x = np.zeros_like(y)
    for i in range(len(y) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x


def check_solution(A, x, b):
    """
    Проверяет решение линейной системы Ax = b.

    Args:
        A: Матрица.
        x: Решение.
        b: Вектор правой части.

    Returns:
        Вектор (Ax - b).
    """
    return A @ x - b

In [7]:
A = np.array([[2, 1, 1],
                [4, 3, 3],
                [8, 7, 9]], dtype=float)
b = np.array([4, 8, 20], dtype=float)

print("A = \n", A)
print("b = \n", b)
print("\n")

P, L, U = LU_decomposition(A)

print("P = \n", P)
print("L = \n", L)
print("U = \n", U)
print("\n")

x = solve_LU(L, U, P, b)
print("x = \n", x)

residual = check_solution(A, x, b)
print("Ax - b = \n", residual)

A = 
 [[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]
b = 
 [ 4.  8. 20.]


P = 
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L = 
 [[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]
U = 
 [[ 8.          7.          9.        ]
 [ 0.         -0.75       -1.25      ]
 [ 0.          0.         -0.66666667]]


x = 
 [ 2. -2.  2.]
Ax - b = 
 [0. 0. 0.]
